// Generated by CoffeeScript 2.2.4
(function() {
  var app;

  $(document).ready(function() {
    return app.init();
  });

  app = {
    text: "この先の道は, ひとりかふたりか, 選ばなきゃいけない, 正解はあるの, I don’t know, リミットはあるの, I don’t know what to do.",
    index: 0,
    chars: 0,
    speed: 100,
    container: ".text .content",
    init: function() {
      this.chars = this.text.length;
      return this.write();
    },
    write: function() {
      $(this.container).append(this.text[this.index]);
      if (this.index < this.chars) {
        this.index++;
        return window.setTimeout(function() {
          return app.write();
        }, this.speed);
      }
    }
  };

}).call(this);

//# sourceMappingURL=tl..js.map
